services:
  lsmcp:
    build:
      context: .
      target: production
    volumes:
      # Mount the working directory at the same path as host for consistent file paths
      - type: bind
        source: ${WORKSPACE_ROOT:-${PWD}}
        target: ${WORKSPACE_ROOT:-${PWD}}
        read_only: false
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=${NODE_ENV:-production}
    working_dir: ${WORKSPACE_ROOT:-${PWD}}
    stdin_open: true
    tty: true
    networks:
      - lsmcp-network

networks:
  lsmcp-network:
    driver: bridge